### ISSUE TITLE
[FR] make release(s)

### ISSUE THREAD

**Issue by ildar** [fabianrost84/SoundRecorder#2]
Hi! I'd love to test your fork. Could you please make a release with recent patches? Thanks a lot!

**Comment by ildar** [comment]
And don't forget mark em with git tags!

**Comment by fbnrst** [comment]
I just did a release. However, remember that this is just my private fork. I really do not know much about Android programming. So, for instance the default storage path is hard-coded for my Motorola Moto E and might not even exist on your device. 

https://github.com/fabianrost84/SoundRecorder/releases/tag/v0.1-alpha

**Comment by ildar** [comment]
Thanks a lot! But you forgot to add the binary apk. Please?

**Comment by fbnrst** [comment]
I think I can do that in the next days.

**Comment by fbnrst** [comment]
Done.
https://github.com/fabianrost84/SoundRecorder/releases/tag/v0.1-alpha

**Comment by ildar** [comment]
Indeed it doesn't work:

> 08-12 01:46:25.550 26115 26115 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
> 08-12 01:46:25.550 26115 26115 E AndroidRuntime:     at com.danielkim.soundrecorder.adapters.FileViewerAdapter.<init>(FileViewerAdapter.java:67)
> 08-12 01:46:25.550 26115 26115 E AndroidRuntime:     at com.danielkim.soundrecorder.fragments.FileViewerFragment.onCreateView(FileViewerFragment.java:51)

**Comment by fbnrst** [comment]
What phone are you using? Looks like it could be the not-existing storage path, as expected.

**Comment by ildar** [comment]
That's CM13 on N5100.
BTW with newer Android you can't simply guess the external storage path: it
is mounted at /storage/$VOLID, e.g. /storage/1234-5678. The internal is as
always at /sdcard.
